version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            cd Python-OC-Lettings-FR-master
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            cd Python-OC-Lettings-FR-master
            flake8 
            python manage.py test home
workflows:
  main:
    jobs:
      - build_and_test
          requires:
            - build_and_test
          filters:
            branches:
              only:
                master
    
